// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX2vD7TGKy51b9P46XrWJmmXPcm_zjqBs',
    appId: '1:866673622650:web:490af526eeefd203dec5c3',
    messagingSenderId: '866673622650',
    projectId: 'drip-emporium-store',
    authDomain: 'drip-emporium-store.firebaseapp.com',
    storageBucket: 'drip-emporium-store.firebasestorage.app',
    measurementId: 'G-YL5HQBX36M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBQWaxYYEo5dXtP2COxiRRR9rfb84hgF8',
    appId: '1:866673622650:android:ef6d632355a2cadddec5c3',
    messagingSenderId: '866673622650',
    projectId: 'drip-emporium-store',
    storageBucket: 'drip-emporium-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0J8g7JNzslo1sMGYtYy4AYA517NYTE1c',
    appId: '1:866673622650:ios:e198d694e0e768a4dec5c3',
    messagingSenderId: '866673622650',
    projectId: 'drip-emporium-store',
    storageBucket: 'drip-emporium-store.firebasestorage.app',
    iosBundleId: 'com.dripemporium.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0J8g7JNzslo1sMGYtYy4AYA517NYTE1c',
    appId: '1:866673622650:ios:9759ee49b0d53d8adec5c3',
    messagingSenderId: '866673622650',
    projectId: 'drip-emporium-store',
    storageBucket: 'drip-emporium-store.firebasestorage.app',
    iosBundleId: 'com.example.dripEmporium',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX2vD7TGKy51b9P46XrWJmmXPcm_zjqBs',
    appId: '1:866673622650:web:c20f26cbf0a456a9dec5c3',
    messagingSenderId: '866673622650',
    projectId: 'drip-emporium-store',
    authDomain: 'drip-emporium-store.firebaseapp.com',
    storageBucket: 'drip-emporium-store.firebasestorage.app',
    measurementId: 'G-LSH4QCHHGC',
  );
}
